@BookLibraryApi_HostAddress = http://localhost:5069

GET {{BookLibraryApi_HostAddress}}/api/books
Accept: application/json

###

GET {{BookLibraryApi_HostAddress}}/api/books/978-0132350884
Accept: application/json

###

POST {{BookLibraryApi_HostAddress}}/api/books
Content-Type: application/json
Accept: application/json

{
    "title":"Harry potter And the sorcerers stone",
    "author":"Jk Rowling",
    "isbn":"962-12371204",
    "year":2000
}

###


PATCH  {{BookLibraryApi_HostAddress}}/api/books/962-12371204
Content-Type: application/json
Accept: application/json

{
    "title":"Harry potter And the sorcerers stones",
    "author":"Jk Rowling and someone else maybe",
    "year":2002
}

###

//bookstatuses

GET {{BookLibraryApi_HostAddress}}/api/bookstatuses
Accept: application/json

###

GET {{BookLibraryApi_HostAddress}}/api/bookstatuses/231609as8d7212io
Accept: application/json

###

POST {{BookLibraryApi_HostAddress}}/api/bookstatuses
Content-Type: application/json
Accept: application/json

{
  "isbn": "978-0132350884",
  "status": false
}

###


PATCH  {{BookLibraryApi_HostAddress}}/api/bookstatuses/231609as8d7212io
Content-Type: application/json
Accept: application/json

{
  "bookstatusId": "231609as8d7212io",
  "isbn": "978-8132350884",
  "status": true
}

###